name: Continuous Delivery Frontend

permissions:
  contents: write

on:
  push:
    branches: [ develop ]
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths
    paths-ignore:
      - 'scripts/**'

jobs:
  version:
    name: Set Semantic Release Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: cycjimmy/semantic-release-action@v5
        id: semantic
        with:
          semantic_version: 24.2.1
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
